platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
target 'RNAudioTaskApp' do
  config = use_native_modules!
  use_react_native!(path: config["reactNativePath"])
  target_installation_prefix = true
end
